### ISSUE TITLE
No compatability with discord.ext

### ISSUE THREAD

**Issue by SystematicError** [astariul/discord_interactive_help#16]
When using this package we pass client as a variable in `Help(client, root)`

When we pass in `discord.Client()` through, it works fine but if some of us use the `discord.ext` library.

For example
```python
from discord.ext import commands

client = commands.Bot(command_prefix = '/')
```

When we pass this through `Help(client, root)` the message is sent however reactions dont work

Thanks, SystematicError

**Comment by ghost** [comment]
Thanks for opening an issue, I didn't know `discord.ext` ^^

---

I tried on my side and met no issue. Can you paste your code here so I can see what's different ?

---

Here is the code I used :

```python
import os
from discord.ext import commands
from discord_interactive import Help, Page

global client
client = commands.Bot(command_prefix='/')

# Define the help tree with `root` as the root, similar to what's in main.py
# [...]

global h
h = Help(client, root)

# Define another help tree if you want (`root2` is the root)
# [...]

global h2
h2 = Help(client, root2)

# Define the bot's commands
@client.command()
async def help(ctx):
    await h.display(ctx.message.author)

@client.command()
async def guild(ctx):
    await h2.display(ctx.message.author)

if __name__ == "__main__":
    token = os.environ.get("DISCORD_BOT_SECRET")
    client.run(token)
```

**Comment by SystematicError** [comment]
Thanks for the response! I'm not really sure what happened, I tried for a good 30 mins before but now I uninstalled and reinstalled the package again and now it's working, probably some corruption, or runtime error who knows.

Edit: I just want to add that both times when it worked and when it didnt I had your code except without the global part and when I run my bot I just do `client.run()` instead of putting it inside the if statement
